### PR TITLE
Allow Minetest Models to be crafted into Minetest Souvenirs

### PR DESCRIPTION
**Pull request by Treer**
Using either glass panes, or an existing nbea wooden frame.

FreeGamers put this mod into a survival server, so after my souvenir broke I couldn't get it back again!

(@Napiophelios - tagging because I often don't notice when people make pull requests)

### CODE REVIEW

**Comment by Treer** [comment]
Also, since this PR hopefully summons you... any chance of putting beautiful mods like lapis onto [ContentDB](https://forum.minetest.net/viewtopic.php?f=18&t=20174)?

**Comment by Napiophelios** [comment]
instead of 'group:pane' maybe makes more sense to use 'xpanes:pane_flat'

             {"group:stick", "xpanes:pane_flat",    "group:stick"},
            {"xpanes:pane_flat",  "nbea:nbox_013", "xpanes:pane_flat"},
            {"group:stick", "xpanes:pane_flat",    "group:stick"}

change that and I'll merge it 

I am not really concerned if my stuff gets put on ConentDB, 
I make stuff mainly for personal use.

If I ever get better at modding, I might add some stuff :)

**Comment by Treer** [comment]
Happy to make that change, but xpanes:pane_flat makes it specific to Minetest Game instead of being general, e.g. group:pane allows xpanes:pane_flat  and will also work in MineClone2 (which uses xpanes but not xpanes:pane_flat), or with obsidian glass panes, though MineClone2 probably isn't a good example as I don't think it has "default", which nbea depends on.

**Comment by Napiophelios** [comment]
ah, damn, you're right :(
quick, change it back !!

If I get some more soundFX and custom textures, 
I could probably find a way to get rid of the dependancy on default mod.

**Comment by Treer** [comment]
A possibility for the glass sound is to search for the first node in minetest.registered_nodes[] that's in the `pane` group, and assign its whole `sounds` table to the souvenir. Though that would mean souvenirs have no sound if the game doesn't have glass panes, perhaps with sound from default:glass as a backup.

(saves adding a new .ogg to the media downloaded to the client)

**Comment by Napiophelios** [comment]
Thanks for the help Treer!

I could really use some help with the mesecon nodes, they are really basic right now, 
If you can suggest any improvements it would be appreciated.

**Comment by Treer** [comment]
I'm not very experienced with mesecons, but the immediate problem I have is I have no idea what the nbea mesecon nodes are or what they are supposed to do - there's no list in the readme and they're just called things like "Core Sample".

Should the expected behavior be obvious if I start playing with them with mesecons?

**Comment by Napiophelios** [comment]
switches and power sources activate them.
monochrome plays music, the others just have basic particle FX when.
I haven't used mesecons very much either.
the whole mod is pretty useless TBH :)

**Pull request merged**
